steps:
  - name: ":golang:"
    plugins:
      golang#v2.0.0:
        version: "1.10"
        import: "${BUILDKITE_GOLANG_IMPORT_PATH}"
    command: 
      - curl https://glide.sh/get | sh
      - make deps-install
      - make build

