env:
  BUILDKTE_GOLANG_IMPORT_PATH: "github.com/ovrclk/akash"
  TEST_DELAY_THREAD_START: 10ms
steps:
  - name: whatever
    command:
      - env
      - id
      - echo $PATH
  - name: ":golang:"
    plugins:
      golang#v2.0.0:
        version: "1.10"
        import: github.com/ovrclk/akash
    command: 
      - curl https://glide.sh/get | sh
      - make deps-install
      - make build
      - make test-vet
      - make test
      # - make integrationdeps-install
      # - make test-integration
