env:
  BUILDKTE_GOLANG_IMPORT_PATH: "github.com/ovrclk/akash"
  TEST_DELAY_THREAD_START: 10ms
steps:

  - name: ":golang: test"
    plugins:
      golang#v2.0.0:
        version: "1.10"
        import: github.com/ovrclk/akash
    command: 
      - curl https://glide.sh/get | sh
      - make deps-install
      - make bins
      - make test-vet
      - make test

  - name: ":golang: coverage"
    plugins:
      golang#v2.0.0:
        version: "1.9"
        import: github.com/ovrclk/akash
    command: 
      - curl https://glide.sh/get | sh
      - make deps-install
      - make coverdeps-install
      - make bins
      - make test-vet
      - make test

  - name: ":golang: integration"
    plugins:
      golang#v2.0.0:
        version: "1.10"
        import: github.com/ovrclk/akash
    command: 
      - curl https://glide.sh/get | sh
      - make deps-install
      - make integrationdeps-install
      - make test-integration
